// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.dalbers.podcastexplorer.dagger;

import com.dalbers.podcastexplorer.data.PodcastMediaPlayer;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

public final class DataModule_ProvideMediaPlayerFactory implements Factory<PodcastMediaPlayer> {
  private final DataModule module;

  public DataModule_ProvideMediaPlayerFactory(DataModule module) {
    assert module != null;
    this.module = module;
  }

  @Override
  public PodcastMediaPlayer get() {
    return Preconditions.checkNotNull(
        module.provideMediaPlayer(), "Cannot return null from a non-@Nullable @Provides method");
  }

  public static Factory<PodcastMediaPlayer> create(DataModule module) {
    return new DataModule_ProvideMediaPlayerFactory(module);
  }

  /** Proxies {@link DataModule#provideMediaPlayer()}. */
  public static PodcastMediaPlayer proxyProvideMediaPlayer(DataModule instance) {
    return instance.provideMediaPlayer();
  }
}
